SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[Topic_Update]    @Topic_ID INT, @Topic_Name VARCHAR(50)
AS 
IF EXISTS (SELECT * FROM dbo.Topic WHERE Topic_ID =  @Topic_ID)
BEGIN 
UPDATE Topic SET Topic_Name=@Topic_Name WHERE Topic_ID=@Topic_ID
END
ELSE
BEGIN
SELECT 'Can not UPDATE '
end
GO
